import type { CalculatorContentDepthData } from "@/components/sections/CalculatorContentDepth";

export const calculatorContentDepth = {
  cgpa: {
    exampleTitle: "Worked example: updating CGPA after a new semester",
    exampleIntro: "Suppose your transcript shows an 8.20 CGPA after 80 completed credits, and this semester you earned an 8.70 SGPA over 20 credits.",
    exampleSteps: [
      "Multiply the old CGPA by completed credits: 8.20 x 80 = 656 grade points.",
      "Multiply the new semester GPA by new credits: 8.70 x 20 = 174 grade points.",
      "Add both totals: 656 + 174 = 830 grade points across 100 credits.",
      "Divide by total credits: 830 / 100 = 8.30 updated CGPA.",
    ],
    interpretation: "The new semester was stronger than the old cumulative average, so the CGPA rises. The increase is modest because 80 older credits already carry most of the weight.",
    differentiatorTitle: "How this differs from SGPA-to-CGPA",
    differentiator: "Use the CGPA calculator when you already know your current cumulative record and want to add one new semester. Use SGPA-to-CGPA when you are entering several semester GPAs from scratch.",
    mistakes: [
      "Do not average CGPA and SGPA directly unless both represent the same number of credits.",
      "Do not mix 4-point and 10-point values in one calculation.",
      "Do not enter attempted credits if your university excludes withdrawn or failed-repeat credits from CGPA.",
    ],
    extraFaqs: [
      { q: "Should I enter credit hours or course count?", a: "Enter credit hours if your transcript uses them. A five-credit lab course should carry more influence than a one-credit seminar." },
      { q: "Can one excellent semester repair a low CGPA?", a: "It helps, but the effect depends on how many credits are already completed. Later semesters usually move CGPA more slowly." },
      { q: "Should internships or pass/fail courses be included?", a: "Only include them if your official transcript assigns grade points and credits to them." },
    ],
  },
  cgpaToPercentage: {
    exampleTitle: "Worked example: converting a 10-point CGPA",
    exampleIntro: "A student has a 7.84 CGPA on a 10-point university scale and needs an estimated percentage for a job form.",
    exampleSteps: [
      "Confirm the institution accepts the common 9.5 multiplier.",
      "Multiply the CGPA by 9.5: 7.84 x 9.5 = 74.48.",
      "Round only if the form requires it; otherwise keep 74.48%.",
      "For official documents, compare the result with the university conversion certificate.",
    ],
    interpretation: "This is a transcript translation, not a fresh grade calculation. It should match visible CGPA input and visible percentage output, with no hidden rating or review claim.",
    differentiatorTitle: "How this differs from SGPA-to-percentage",
    differentiator: "CGPA-to-percentage converts your full cumulative academic record. SGPA-to-percentage converts one semester only, which may be higher or lower than your overall percentage.",
    mistakes: [
      "Do not use the 10-point formula for a 4-point GPA transcript.",
      "Do not round up to pass an eligibility cutoff unless the institution says rounding is allowed.",
      "Do not treat this estimate as a registrar-issued equivalency certificate.",
    ],
    extraFaqs: [
      { q: "What percentage is an 8.0 CGPA?", a: "Using the common 9.5 formula, 8.0 x 9.5 = 76.0%." },
      { q: "Can a university use CGPA x 10 instead?", a: "Yes. Some institutions use a direct multiplier or a table, which is why official conversion rules matter." },
      { q: "Why does a 4-point CGPA need a different conversion?", a: "A 4-point scale has different grade boundaries, so using the 10-point multiplier would overstate the percentage." },
    ],
  },
  finalGrade: {
    exampleTitle: "Worked example: score needed on the final exam",
    exampleIntro: "Imagine your current course grade is 82%, your final exam is worth 30%, and you want an 85% overall grade.",
    exampleSteps: [
      "The completed work is worth 70% of the course: 82 x 0.70 = 57.4 points.",
      "The target course total is 85 points.",
      "Remaining points needed from the final: 85 - 57.4 = 27.6.",
      "Divide by the final weight: 27.6 / 0.30 = 92%.",
    ],
    interpretation: "You need about 92% on the final to finish with 85%. If that number is above 100%, the target is mathematically out of reach under the current weighting.",
    differentiatorTitle: "How this differs from semester grade",
    differentiator: "The final grade calculator solves backward from a target. The semester grade calculator solves forward from completed category scores and weights.",
    mistakes: [
      "Do not enter the final weight as 0.30 if the input asks for a percent value.",
      "Do not use your current LMS grade if ungraded assignments are being counted as zero.",
      "Do not forget extra credit or dropped lowest-score rules if your syllabus uses them.",
    ],
    extraFaqs: [
      { q: "What if the needed final score is over 100%?", a: "That means the target cannot be reached through the final exam alone unless extra credit or a grade replacement rule applies." },
      { q: "Can I use this before all assignments are graded?", a: "Yes, but your current grade must represent only the work completed so far and the remaining final weight must be accurate." },
      { q: "Does this calculate my final exam grade or course grade?", a: "It calculates the exam score needed to reach a target course grade." },
    ],
  },
  semesterGrade: {
    exampleTitle: "Worked example: weighted semester categories",
    exampleIntro: "A course uses homework 20%, quizzes 10%, midterm 30%, project 15%, and final exam 25%. Your scores are 94, 86, 78, 91, and 88.",
    exampleSteps: [
      "Convert weights to decimals and multiply: 94 x 0.20 = 18.8.",
      "Add each weighted contribution: 8.6 + 23.4 + 13.65 + 22.0.",
      "Total all category contributions: 18.8 + 8.6 + 23.4 + 13.65 + 22.0 = 86.45.",
      "Your semester grade is 86.45%, before any instructor rounding rule.",
    ],
    interpretation: "The midterm and final matter most because they carry the largest weights. A small improvement in a heavily weighted category changes the final result more than a big improvement in a tiny category.",
    differentiatorTitle: "How this differs from average grade",
    differentiator: "Average grade is best when every score has equal weight or when you are averaging one category. Semester grade is for full syllabus weighting across different category types.",
    mistakes: [
      "Do not average all assignments together if the syllabus uses category weights.",
      "Do not include future blank assignments as zero unless your instructor already counts them as zero.",
      "Do not let category weights exceed or fall below 100% without understanding normalization.",
    ],
    extraFaqs: [
      { q: "Can this handle a missing category?", a: "Yes. If a category has not happened yet, calculate a current-grade snapshot with completed categories only, then recalculate later." },
      { q: "Should I enter rounded category averages?", a: "Use the most precise values available from your gradebook to avoid small rounding differences." },
      { q: "What if the final exam is optional?", a: "Calculate once with the final included and once without it, then follow your syllabus rule for exemptions." },
    ],
  },
  sgpaToCgpa: {
    exampleTitle: "Worked example: combining semester SGPAs",
    exampleIntro: "You completed three semesters: 8.1 over 18 credits, 8.6 over 20 credits, and 7.9 over 22 credits.",
    exampleSteps: [
      "Convert each semester into grade points: 8.1 x 18 = 145.8.",
      "Add the other semesters: 8.6 x 20 = 172 and 7.9 x 22 = 173.8.",
      "Total grade points are 491.6 across 60 credits.",
      "CGPA = 491.6 / 60 = 8.19.",
    ],
    interpretation: "The third semester has the most credits, so it influences CGPA slightly more than the first two semesters.",
    differentiatorTitle: "How this differs from the CGPA calculator",
    differentiator: "SGPA-to-CGPA starts with individual semester values. The CGPA calculator starts with an existing cumulative value and adds new data.",
    mistakes: [
      "Do not use a simple average when semesters have different credit loads.",
      "Do not include remedial or audit semesters unless they appear in official CGPA credits.",
      "Do not combine percentage marks and SGPA values in the same input table.",
    ],
    extraFaqs: [
      { q: "Can I calculate CGPA without credits?", a: "Yes, if every semester has equal credit load. If credits differ, use weighted credits for accuracy." },
      { q: "Why is my CGPA lower than the average of my SGPAs?", a: "A lower-SGPA semester may carry more credits, pulling the weighted average down." },
      { q: "Can I include future expected SGPA?", a: "Yes for planning, but label it as a projection rather than an official CGPA." },
    ],
  },
  sgpaToPercentage: {
    exampleTitle: "Worked example: converting one semester SGPA",
    exampleIntro: "A student earns 8.35 SGPA in semester five and needs the semester percentage for a placement form.",
    exampleSteps: [
      "Confirm the semester result is on a 10-point scale.",
      "Use the common formula: percentage = SGPA x 9.5.",
      "Calculate 8.35 x 9.5 = 79.325%.",
      "Report 79.33% only if the form allows two-decimal rounding.",
    ],
    interpretation: "This result describes one semester only. It should not be submitted as your full-degree percentage unless the form specifically asks for semester percentage.",
    differentiatorTitle: "How this differs from CGPA-to-percentage",
    differentiator: "SGPA-to-percentage is term-specific. CGPA-to-percentage converts the cumulative performance across all completed semesters.",
    mistakes: [
      "Do not use SGPA when the form asks for overall CGPA percentage.",
      "Do not assume the 9.5 multiplier if your university publishes a different table.",
      "Do not convert a 4-point SGPA with the 10-point formula.",
    ],
    extraFaqs: [
      { q: "What is 8.5 SGPA in percentage?", a: "Using the common 9.5 multiplier, 8.5 SGPA equals 80.75%." },
      { q: "Is SGPA-to-percentage useful for semester merit lists?", a: "It can help you estimate, but official merit lists use the university's own rules." },
      { q: "Can I average semester percentages to get degree percentage?", a: "Only if every semester has equal credits. Otherwise use credit-weighted CGPA conversion." },
    ],
  },
  percentageToCgpa: {
    exampleTitle: "Worked example: converting percentage to 10-point CGPA",
    exampleIntro: "Suppose your transcript shows 76% and an application form asks for CGPA on a 10-point scale.",
    exampleSteps: [
      "Use the reverse of the common 9.5 formula: CGPA = percentage / 9.5.",
      "Calculate 76 / 9.5 = 8.00.",
      "Keep the result as 8.00 CGPA unless the form asks for one decimal.",
      "Attach the original transcript if the application allows it.",
    ],
    interpretation: "This conversion is an estimate for forms that require CGPA. It does not replace the grading scale printed by your original institution.",
    differentiatorTitle: "How this differs from marks percentage",
    differentiator: "Percentage-to-CGPA translates an already known final percentage into grade points. Marks percentage calculates the percentage first from obtained and total marks.",
    mistakes: [
      "Do not convert individual subject percentages unless the form asks for subject CGPA.",
      "Do not cap or inflate results manually near eligibility cutoffs.",
      "Do not use this for credential evaluation where official agencies provide their own conversion.",
    ],
    extraFaqs: [
      { q: "What CGPA is 75%?", a: "Using the common 9.5 divisor, 75 / 9.5 = 7.89 CGPA." },
      { q: "Why does the calculator show decimals?", a: "Because direct conversion rarely lands on a clean tenth; decimals preserve the closest estimate." },
      { q: "Can I convert class 12 percentage to CGPA?", a: "Only if the receiving institution accepts this formula. School boards often use different grading systems." },
    ],
  },
  marksPercentage: {
    exampleTitle: "Worked example: subject-wise marks percentage",
    exampleIntro: "You scored 78/100 in math, 64/80 in physics, and 42/50 in a lab practical.",
    exampleSteps: [
      "Add obtained marks: 78 + 64 + 42 = 184.",
      "Add total marks: 100 + 80 + 50 = 230.",
      "Divide obtained by total: 184 / 230 = 0.80.",
      "Multiply by 100 to get 80%.",
    ],
    interpretation: "This weighted-by-marks method is more accurate than averaging 78%, 80%, and 84%, because each subject has a different maximum mark value.",
    differentiatorTitle: "How this differs from percentage calculator",
    differentiator: "Marks percentage is built for exam scores and subject totals. The general percentage calculator is for everyday percent-of, increase, decrease, and reverse-percentage problems.",
    mistakes: [
      "Do not average subject percentages when total marks differ.",
      "Do not enter grade points or CGPA in a marks calculator.",
      "Do not forget practical, lab, or internal-assessment marks if they appear in total marks.",
    ],
    extraFaqs: [
      { q: "Should I include absent subjects?", a: "Follow your official result rules. If the subject is counted in total marks, include it." },
      { q: "Can this calculate aggregate percentage?", a: "Yes. Add all obtained marks and all maximum marks across subjects." },
      { q: "Why is aggregate different from average percentage?", a: "Aggregate uses marks weight. Average percentage gives each subject equal weight even if maximum marks differ." },
    ],
  },
  percentage: {
    exampleTitle: "Worked example: increase and reverse percentage",
    exampleIntro: "A fee rises from 1,200 to 1,380, and you want the percentage increase. Later, you see a discounted price of 920 after 20% off.",
    exampleSteps: [
      "Increase amount: 1,380 - 1,200 = 180.",
      "Percentage increase: 180 / 1,200 x 100 = 15%.",
      "Reverse discount original: 920 / (1 - 0.20) = 1,150.",
      "The original price before discount was 1,150.",
    ],
    interpretation: "The same calculator handles different percent relationships, but the inputs mean different things depending on the selected mode.",
    differentiatorTitle: "How this differs from marks percentage",
    differentiator: "Use this page for general math, finance, discounts, and percent change. Use marks percentage when your inputs are obtained marks and total exam marks.",
    mistakes: [
      "Do not confuse percentage points with percent change.",
      "Do not divide by the new value when calculating percent increase from an old value.",
      "Do not use reverse percentage mode when you simply need X% of a number.",
    ],
    extraFaqs: [
      { q: "What is the difference between 10% and 10 percentage points?", a: "10% is relative to a base value. 10 percentage points is an absolute movement, such as 60% to 70%." },
      { q: "Can this calculate discounts?", a: "Yes. Use percentage-of for the discount amount or reverse percentage to recover the original price." },
      { q: "Why does percent change use the old value as the base?", a: "Because the change is measured relative to where the value started." },
    ],
  },
  loan: {
    exampleTitle: "Worked example: fixed-rate monthly payment",
    exampleIntro: "You borrow 25,000 at 8% annual interest for 5 years and want an estimated monthly payment.",
    exampleSteps: [
      "Convert annual interest to a monthly decimal rate: 0.08 / 12 = 0.006667.",
      "Convert years to months: 5 x 12 = 60 payments.",
      "Apply the EMI formula using principal 25,000, monthly rate 0.006667, and 60 months.",
      "The estimated payment is about 506.91 per month before fees, taxes, or insurance.",
    ],
    interpretation: "A longer term would reduce the monthly payment but increase total interest. A lower rate reduces both the payment and total interest.",
    differentiatorTitle: "How this differs from simple interest math",
    differentiator: "This page estimates amortized payments where each installment includes interest plus principal. Simple percentage math cannot show the repayment balance over time.",
    mistakes: [
      "Do not compare loans only by monthly payment; compare total interest too.",
      "Do not enter monthly interest as if it were annual interest.",
      "Do not assume the estimate includes lender fees, taxes, insurance, or prepayment penalties.",
    ],
    extraFaqs: [
      { q: "Why is early loan interest higher?", a: "At the start, the outstanding principal is largest, so more of each payment goes to interest." },
      { q: "Does making extra payments help?", a: "Extra principal payments usually reduce interest and shorten payoff time, unless a prepayment penalty applies." },
      { q: "Can I use this for student loans?", a: "Yes for fixed-rate amortized student loans, but deferment, subsidies, and variable rates may change the real schedule." },
    ],
  },
  tip: {
    exampleTitle: "Worked example: splitting a restaurant bill",
    exampleIntro: "A group of four has a 96.40 bill and wants to leave an 18% tip.",
    exampleSteps: [
      "Calculate the tip: 96.40 x 0.18 = 17.35.",
      "Add tip to the bill: 96.40 + 17.35 = 113.75.",
      "Split across four people: 113.75 / 4 = 28.44 each.",
      "Round up if your group prefers an easier cash amount.",
    ],
    interpretation: "The per-person amount changes if tax is included before tipping, so decide whether your group tips on the pre-tax or post-tax amount.",
    differentiatorTitle: "How this differs from percentage calculator",
    differentiator: "The general percentage calculator can find the tip amount, but this page also handles bill totals and group splitting in one flow.",
    mistakes: [
      "Do not split the pre-tip bill if the group agreed to split the full total.",
      "Do not forget service charges that may already include gratuity.",
      "Do not round each person's share too early, or the final total may be short.",
    ],
    extraFaqs: [
      { q: "Should I tip before or after tax?", a: "Local custom varies. Many people tip on the pre-tax subtotal, while others use the final bill for simplicity." },
      { q: "What if one person orders much more?", a: "Use the calculator for the shared total only if everyone agrees to an even split." },
      { q: "Can I include a service charge?", a: "Yes, but check whether it is already a gratuity before adding a separate tip." },
    ],
  },
  password: {
    exampleTitle: "Worked example: choosing a safer password rule",
    exampleIntro: "You need a password for a financial account and can choose length, symbols, numbers, and mixed-case letters.",
    exampleSteps: [
      "Choose at least 16 characters for important accounts.",
      "Include uppercase, lowercase, numbers, and symbols if the website allows them.",
      "Generate a random value instead of editing a memorable phrase by hand.",
      "Store it in a password manager so you do not reuse it elsewhere.",
    ],
    interpretation: "Length and randomness matter more than clever substitutions. A random 16-character password is usually stronger than a shorter password with predictable symbol swaps.",
    differentiatorTitle: "How this differs from academic calculators",
    differentiator: "This tool is security-focused rather than grade-focused, so its quality comes from random generation options, entropy guidance, and copy-safe workflow.",
    mistakes: [
      "Do not reuse the same generated password on multiple websites.",
      "Do not remove symbols just to make a password easier to remember unless the site rejects them.",
      "Do not share generated passwords in chat, email, or screenshots.",
    ],
    extraFaqs: [
      { q: "Is a longer password always stronger?", a: "Length helps a lot, but it should also be random and unique to the account." },
      { q: "Should I memorize generated passwords?", a: "For most accounts, store them in a trusted password manager instead of trying to memorize each one." },
      { q: "Are passphrases safe?", a: "Long random passphrases can be safe, but short or famous phrases are easy to guess." },
    ],
  },
} satisfies Record<string, CalculatorContentDepthData>;
