const legalNavLabels: Record<string, string> = {
  acceptance: "Acceptance",
  "service-description": "Service",
  "no-professional-advice": "No Advice",
  accuracy: "Accuracy",
  "acceptable-use": "Use",
  adsense: "Advertising",
  "advertising-adsense": "Ads",
  "intellectual-property": "IP Rights",
  privacy: "Privacy",
  "privacy-policy": "Privacy",
  "third-party": "Links",
  "third-party-links": "Links",
  "prohibited-content": "Content Rules",
  warranties: "Warranties",
  "disclaimer-warranties": "Warranties",
  liability: "Liability",
  "limitation-liability": "Liability",
  indemnification: "Indemnity",
  age: "Age",
  "age-requirement": "Age",
  changes: "Changes",
  "changes-terms": "Changes",
  governing: "Law",
  "governing-law": "Law",
  entire: "Agreement",
  "entire-agreement": "Agreement",
  contact: "Contact",
  "information-collect": "Data",
  "how-we-use": "Data Use",
  "google-analytics": "Analytics",
  "cookies-advertising": "Cookies",
  "google-adsense": "AdSense",
  "browser-inputs": "Inputs",
  "children-privacy": "Children",
  "gdpr-rights": "GDPR Rights",
  "ccpa-rights": "CCPA Rights",
  "data-security": "Security",
  "what-are-cookies": "Cookies",
  "why-we-use": "Why Cookies",
  "cookies-we-use": "Types",
  "third-party-cookies": "Third Party",
  "managing-cookies": "Manage",
  "california-residents": "California",
  updates: "Updates",
  general: "Information",
  professional: "No Advice",
  "user-responsibility": "User Duties",
};

export function getLegalNavLabel(id: string, title: string) {
  return legalNavLabels[id] ?? title.replace(/^\d+\.\s*/, "");
}
