export const ROUTES = {
  home: "/",
  about: "/about",
  contact: "/contact",
  faq: "/faq",
  blog: "/blog",
  author: "/author",
  privacyPolicy: "/privacy-policy",
  cookies: "/cookie-policy",
  terms: "/terms-of-service",
  disclaimer: "/disclaimer",

  gradeCurveCalculator: "/grade-curve-calculator",
  averageGradeCalculator: "/average-grade-calculator",
  semesterGradeCalculator: "/semester-grade-calculator",
  gpaCalculator: "/gpa-calculator",
  cgpaCalculator: "/cgpa-calculator",
  finalGradeCalculator: "/final-grade-calculator",
  cgpaToPercentage: "/cgpa-to-percentage",
  sgpaToCgpa: "/sgpa-to-cgpa",
  sgpaToPercentage: "/sgpa-to-percentage",
  percentageToCgpa: "/percentage-to-cgpa",
  marksPercentageCalculator: "/marks-percentage-calculator",
  percentageCalculator: "/percentage-calculator",
  loanCalculator: "/loan-calculator",
  tipCalculator: "/tip-calculator",
  passwordGenerator: "/password-generator",
} as const;

export const CALCULATOR_ROUTES = [
  ROUTES.gradeCurveCalculator,
  ROUTES.averageGradeCalculator,
  ROUTES.semesterGradeCalculator,
  ROUTES.gpaCalculator,
  ROUTES.cgpaCalculator,
  ROUTES.finalGradeCalculator,
  ROUTES.cgpaToPercentage,
  ROUTES.sgpaToCgpa,
  ROUTES.sgpaToPercentage,
  ROUTES.percentageToCgpa,
  ROUTES.marksPercentageCalculator,
  ROUTES.percentageCalculator,
  ROUTES.loanCalculator,
  ROUTES.tipCalculator,
  ROUTES.passwordGenerator,
] as const;

export const STATIC_ROUTES = [
  ROUTES.home,
  ROUTES.about,
  ROUTES.contact,
  ROUTES.faq,
  ROUTES.blog,
  ROUTES.privacyPolicy,
  ROUTES.cookies,
  ROUTES.terms,
  ROUTES.disclaimer,
] as const;
