'use client';

import { motion } from "framer-motion";
import Link from "next/link";
import { useState } from "react";
import type { IconType } from "react-icons";
import { FiArrowRight, FiFileText, FiChevronDown, FiChevronUp, FiBook, FiUsers, FiShield, FiCreditCard, FiGlobe, FiAlertTriangle, FiMail, FiLock, FiSettings } from "react-icons/fi";
import GlobalCTA from "@/components/ui/GlobalCTA";
import { ROUTES } from "@/lib/routes";
import { ContactMethodLink } from "@/components/ui/ContactMethodLink";
import { LinkedText } from "@/components/ui/LinkedText";
import { getLegalNavLabel } from "@/lib/legalNav";

// ─── Animations ─────────────────────────────────────────────────────────────
const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 24 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.55, delay, ease: [0.22, 1, 0.36, 1] as const },
});

// ─── Data ────────────────────────────────────────────────────────────────────
const lastUpdated = "July 8, 2026";

const features = [
  {
    icon: <FiFileText className="text-blue-500" size={28} />,
    title: "Agreement",
    description: "Applies to all users 18+",
  },
  {
    icon: <FiGlobe className="text-green-500" size={28} />,
    title: "Free Service",
    description: "No payment required",
  },
  {
    icon: <FiAlertTriangle className="text-amber-500" size={28} />,
    title: "No Advice",
    description: "Verify results independently",
  },
  {
    icon: <FiCreditCard className="text-purple-500" size={28} />,
    title: "AdSense",
    description: "Ad policy compliance",
  },
];

interface TermsSection {
  id: string;
  title: string;
  icon: IconType;
  color: string;
  summary: string;
  content: string;
  highlights: string[];
  prohibitedActivities?: string[];
  adSensePolicies?: Array<{
    policy: string;
    description: string;
  }>;
  notAdviceTypes?: string[];
  excludedDamages?: string[];
  contactMethods?: Array<{
    type: string;
    value: string;
  }>;
}

const sections: TermsSection[] = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    icon: FiFileText,
    color: "blue",
    summary: "Users must be 18+ and agree to be legally bound by these terms",
    content: `By accessing or using Average Grade Calculator ("the Website," "we," "our," or "us"), located at https://www.averagegradecalculator.com, you confirm that you are at least 18 years of age and agree to be legally bound by these Terms of Service ("Terms"). If you do not agree with any part of these Terms, please discontinue use of the Website immediately.

These Terms apply to all visitors, users, and anyone who accesses or uses the Website.`,
    highlights: [
      "Must be 18+ years old",
      "Legally binding agreement",
      "Applies to all users and visitors"
    ]
  },
  {
    id: "service-description",
    title: "2. Description of Service",
    icon: FiSettings,
    color: "green",
    summary: "Free browser-based website service",
    content: `Average Grade Calculator provides a free, browser-based website service for general informational use.

No account registration or personal information is required to use this Website.`,
    highlights: [
      "Browser-based service",
      "Completely free to use",
      "No registration required"
    ]
  },
  {
    id: "no-professional-advice",
    title: "3. No Professional or Expert Advice",
    icon: FiUsers,
    color: "amber",
    summary: "Results are informational only - not professional advice",
    content: `This Website is for general informational and educational purposes only. Results generated by this Website do not constitute professional or licensed expert advice.

You should always verify results independently and consult a qualified professional before making any significant decisions based on website results. Average Grade Calculator accepts no responsibility for decisions made based on results from this Website.`,
    highlights: [
      "Informational purposes only",
      "Not professional advice",
      "Always verify results independently"
    ],
    notAdviceTypes: [
      "Professional advice",
      "Licensed expert advice"
    ]
  },
  {
    id: "accuracy",
    title: "4. Accuracy of Results",
    icon: FiAlertTriangle,
    color: "orange",
    summary: "No guarantees on accuracy - results should be treated as estimates",
    content: `While we make every effort to keep results accurate and up to date, we make no guarantees regarding the accuracy, completeness, or suitability of any result. Outputs may vary based on user inputs, rounding methods, or changes in standards and regulations. All results should be treated as estimates only.`,
    highlights: [
      "No accuracy guarantees",
      "Results may vary based on inputs",
      "Treat all results as estimates"
    ]
  },
  {
    id: "acceptable-use",
    title: "5. Acceptable Use Policy",
    icon: FiShield,
    color: "purple",
    summary: "Lawful use only - prohibited activities strictly enforced",
    content: `You agree to use this Website only for lawful purposes. The following activities are strictly prohibited:

• Attempting to reverse-engineer, copy, scrape, or redistribute the Website's code or content
• Using automated bots, scripts, or crawlers to mass-query the Website or harvest content
• Attempting to disrupt, overload, or interfere with the Website's servers or infrastructure
• Using the Website to transmit malware, spam, or any harmful software
• Accessing the Website through any means other than the standard user interface
• Violating any applicable local, national, or international law or regulation`,
    highlights: [
      "Lawful purposes only",
      "No automated scraping or bots",
      "No malware or harmful software"
    ],
    prohibitedActivities: [
      "Reverse-engineering or scraping content",
      "Using automated bots or scripts",
      "Disrupting servers or infrastructure",
      "Transmitting malware or spam",
      "Non-standard website access",
      "Violating applicable laws"
    ]
  },
  {
    id: "advertising-adsense",
    title: "6. Advertising: Google AdSense Policy Compliance",
    icon: FiCreditCard,
    color: "indigo",
    summary: "Google AdSense advertising with strict fraud prevention policies",
    content: `Average Grade Calculator displays advertisements through Google AdSense. By using this Website, you acknowledge the following advertising terms:

No Click Manipulation: You must not click on advertisements displayed on this Website for any fraudulent or artificial purpose. You must not use any program, script, robot, or any other automated means to generate clicks or impressions on ads.

No Incentivized Clicks: Average Grade Calculator does not and will not ask users to click on ads, offer rewards for clicking ads, or use language such as "click here," "support us," or "visit our sponsors" to direct attention to advertisements. Any such activity violates Google AdSense program policies.

No Ad Interference: You must not block, hide, modify, or interfere with the display of advertisements on this Website.

Third-Party Ad Content: We do not control the content of ads served by Google AdSense and are not responsible for the products, services, or claims made in third-party advertisements. Clicking on ads may redirect you to third-party websites governed by their own terms.

AdSense DART Cookies: Google AdSense uses DART cookies to serve ads based on your visit to this Website and other sites on the internet. You may opt out of DART cookies by visiting: https://policies.google.com/technologies/ads

We fully comply with Google AdSense Program Policies. Any violation of these policies by users may result in legal action and/or reporting to Google.`,
    highlights: [
      "No fraudulent ad clicking",
      "No click incentives offered",
      "No ad interference allowed"
    ],
    adSensePolicies: [
      { policy: "No Click Manipulation", description: "No fraudulent or artificial ad clicks" },
      { policy: "No Incentivized Clicks", description: "No rewards or encouragement for clicking ads" },
      { policy: "No Ad Interference", description: "Cannot block, hide, or modify ad display" },
      { policy: "Third-Party Content", description: "We don't control ad content from Google AdSense" },
      { policy: "DART Cookies", description: "Google uses cookies for personalized ads - opt out available" }
    ]
  },
  {
    id: "intellectual-property",
    title: "7. Intellectual Property",
    icon: FiLock,
    color: "red",
    summary: "All content protected by copyright - personal use only",
    content: `All content on Average Grade Calculator, including but not limited to logic, design, graphics, text, layouts, and code, is the exclusive property of Average Grade Calculator and is protected under applicable copyright and intellectual property laws.

You may use the Website for personal, non-commercial purposes only. Reproduction, redistribution, scraping, or commercial use of any content without prior written permission is strictly prohibited.

The name "Average Grade Calculator," its logo, and any associated branding may not be used without express written consent.`,
    highlights: [
      "All content is protected by copyright",
      "Personal, non-commercial use only",
      "Written permission required for commercial use"
    ]
  },
  {
    id: "privacy-policy",
    title: "8. Privacy Policy",
    icon: FiShield,
    color: "indigo",
    summary: "Privacy policy incorporated by reference - covers data practices",
    content: `Your use of this Website is also governed by our Privacy Policy, which is incorporated into these Terms by reference. Our Privacy Policy explains how we handle information, cookies, and third-party advertising data including Google AdSense.

Please review our Privacy Policy at: https://www.averagegradecalculator.com/privacy-policy

By using this Website, you consent to the data practices described in our Privacy Policy.`,
    highlights: [
      "Privacy Policy incorporated by reference",
      "Covers data and cookie practices",
      "User consent required"
    ]
  },
  {
    id: "third-party-links",
    title: "9. Third-Party Links and Services",
    icon: FiGlobe,
    color: "indigo",
    summary: "External links for reference only - no endorsement or responsibility",
    content: `Our Website may contain links to third-party websites for reference or informational purposes. We do not endorse, control, or accept responsibility for the content, terms, or privacy practices of any third-party website. Visiting linked sites is entirely at your own risk.

We are not affiliated with Google, and our use of Google AdSense does not imply any endorsement by Google of our Website or its content.`,
    highlights: [
      "Links for reference only",
      "No endorsement of third-party sites",
      "Visit at your own risk"
    ]
  },
  {
    id: "prohibited-content",
    title: "10. Prohibited Content & Compliance",
    icon: FiAlertTriangle,
    color: "rose",
    summary: "Strict content standards for user submissions and interactions",
    content: `Average Grade Calculator does not host, publish, or permit the following types of content in any user-submitted form (such as contact messages or feedback):

• Illegal, hateful, defamatory, or discriminatory content
• Content that promotes violence, self-harm, or illegal activities
• Sexually explicit or adult content
• Content that infringes on intellectual property rights
• Spam, phishing, or malicious code

We reserve the right to remove any content and block any user that violates these standards without notice.`,
    highlights: [
      "Strict content standards",
      "No illegal or harmful content",
      "Right to remove violating content"
    ],
    prohibitedActivities: [
      "Illegal, hateful, or discriminatory content",
      "Violence or self-harm promotion",
      "Sexually explicit content",
      "IP infringement",
      "Spam or malicious code"
    ]
  },
  {
    id: "disclaimer-warranties",
    title: "11. Disclaimer of Warranties",
    icon: FiSettings,
    color: "indigo",
    summary: "Service provided 'as is' without any warranties",
    content: `Average Grade Calculator is provided on an "as is" and "as available" basis. We make no warranties, express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the Website will be uninterrupted, error-free, or free of viruses or other harmful components.`,
    highlights: [
      "Service provided 'as is'",
      "No express or implied warranties",
      "No guarantee of error-free operation"
    ]
  },
  {
    id: "limitation-liability",
    title: "12. Limitation of Liability",
    icon: FiShield,
    color: "violet",
    summary: "Limited liability for any damages arising from website use",
    content: `To the maximum extent permitted by applicable law, Average Grade Calculator and its owners, operators, employees, and contributors shall not be liable for any direct, indirect, incidental, consequential, special, or punitive damages arising from:

• Your use of or inability to use the Website
• Reliance on any results or information provided on the Website
• Errors, omissions, or inaccuracies in outputs
• Unauthorized access to or alteration of your data
• Any conduct or content of third parties on or through the Website`,
    highlights: [
      "No liability for direct or indirect damages",
      "No liability for result reliance",
      "Maximum legal protection"
    ],
    excludedDamages: [
      "Use or inability to use the Website",
      "Reliance on website results",
      "Errors or inaccuracies in outputs",
      "Unauthorized data access",
      "Third-party conduct or content"
    ]
  },
  {
    id: "indemnification",
    title: "13. Indemnification",
    icon: FiUsers,
    color: "indigo",
    summary: "Users must protect Average Grade Calculator from claims arising from their use",
    content: `You agree to indemnify, defend, and hold harmless Average Grade Calculator and its operators from any claims, liabilities, damages, losses, or expenses (including reasonable legal fees) arising out of or related to your use of the Website, violation of these Terms, or violation of any third-party rights.`,
    highlights: [
      "User protects website from claims",
      "Covers legal fees and damages",
      "Applies to terms violations"
    ]
  },
  {
    id: "age-requirement",
    title: "14. Age Requirement",
    icon: FiUsers,
    color: "amber",
    summary: "Must be 18+ or have parental supervision for minors",
    content: `You must be at least 18 years of age to use this Website. By using the Website, you confirm that you meet this age requirement. If you are under 18, you may use this Website only under the supervision of a parent or legal guardian who agrees to be bound by these Terms.

This Website is not directed at children under the age of 13. We do not knowingly collect any personal information from children under 13.`,
    highlights: [
      "Must be 18+ to use",
      "Parental supervision for minors",
      "Not directed at under-13 children"
    ]
  },
  {
    id: "changes-terms",
    title: "15. Changes to These Terms",
    icon: FiBook,
    color: "indigo",
    summary: "Terms may be updated - continued use implies acceptance",
    content: `We reserve the right to update or modify these Terms at any time. Changes take effect immediately upon posting to this page. The "Last Updated" date at the top reflects the most recent revision. Your continued use of the Website after changes are posted constitutes your acceptance of the updated Terms. We encourage you to review this page periodically.`,
    highlights: [
      "Terms may be updated anytime",
      "Changes effective immediately",
      "Continued use implies acceptance"
    ]
  },
  {
    id: "governing-law",
    title: "16. Governing Law",
    icon: FiGlobe,
    color: "indigo",
    summary: "Governed by US law with flexible jurisdiction",
    content: `These Terms shall be governed by and construed in accordance with the laws of the United States. Any disputes arising from these Terms or your use of the Website shall be subject to the jurisdiction of the courts of the United States. We reserve the right to bring proceedings in the courts of the country where you reside.`,
    highlights: [
      "Governed by US law",
      "US court jurisdiction",
      "Flexible jurisdiction for users"
    ]
  },
  {
    id: "entire-agreement",
    title: "17. Entire Agreement",
    icon: FiFileText,
    color: "purple",
    summary: "Terms and Privacy Policy constitute complete agreement",
    content: `These Terms, together with our Privacy Policy, constitute the entire agreement between you and Average Grade Calculator regarding your use of the Website and supersede any prior agreements or understandings.`,
    highlights: [
      "Complete agreement with Privacy Policy",
      "Supersedes prior agreements",
      "Comprehensive legal framework"
    ]
  },
  {
    id: "contact",
    title: "18. Contact Us",
    icon: FiMail,
    color: "green",
    summary: "Questions about these terms welcomed",
    content: `For questions about these Terms of Service, contact the Average Grade Calculator team.
Use the contact options below for support.`,
    highlights: [
      "Terms support",
      "Website and email",
      "Prompt response"
    ],
    contactMethods: [
      { type: "Website", value: "https://www.averagegradecalculator.com" },
      { type: "Email", value: "support@averagegradecalculator.com" }
    ]
  },
];

// ─── Helper Functions ────────────────────────────────────────────────────────
const getColorClasses = (color: string) => {
  const colorMap: Record<string, { bg: string; border: string; text: string; icon: string }> = {
    blue: { bg: "bg-blue-50 dark:bg-blue-500/10", border: "border-blue-200 dark:border-blue-500/20", text: "text-blue-600 dark:text-blue-400", icon: "text-blue-500" },
    green: { bg: "bg-green-50 dark:bg-green-500/10", border: "border-green-200 dark:border-green-500/20", text: "text-green-600 dark:text-green-400", icon: "text-green-500" },
    amber: { bg: "bg-amber-50 dark:bg-amber-500/10", border: "border-amber-200 dark:border-amber-500/20", text: "text-amber-600 dark:text-amber-400", icon: "text-amber-500" },
    purple: { bg: "bg-purple-50 dark:bg-purple-500/10", border: "border-purple-200 dark:border-purple-500/20", text: "text-purple-600 dark:text-purple-400", icon: "text-purple-500" },
    orange: { bg: "bg-orange-50 dark:bg-orange-500/10", border: "border-orange-200 dark:border-orange-500/20", text: "text-orange-600 dark:text-orange-400", icon: "text-orange-500" },
    navyAliasB: { bg: "bg-indigo-50 dark:bg-indigo-500/10", border: "border-indigo-200 dark:border-indigo-500/20", text: "text-indigo-600 dark:text-[var(--brand-text)]", icon: "text-indigo-500" },
    navyAliasA: { bg: "bg-indigo-50 dark:bg-indigo-500/10", border: "border-indigo-200 dark:border-indigo-500/20", text: "text-indigo-600 dark:text-[var(--brand-text)]", icon: "text-indigo-500" },
    red: { bg: "bg-red-50 dark:bg-red-500/10", border: "border-red-200 dark:border-red-500/20", text: "text-red-600 dark:text-red-400", icon: "text-red-500" },
    indigo: { bg: "bg-indigo-50 dark:bg-indigo-500/10", border: "border-indigo-200 dark:border-indigo-500/20", text: "text-indigo-600 dark:text-[var(--brand-text)]", icon: "text-indigo-500" },
    slate: { bg: "bg-slate-50 dark:bg-slate-500/10", border: "border-slate-200 dark:border-slate-500/20", text: "text-slate-600 dark:text-slate-400", icon: "text-slate-500" },
    violet: { bg: "bg-violet-50 dark:bg-violet-500/10", border: "border-violet-200 dark:border-violet-500/20", text: "text-violet-600 dark:text-violet-400", icon: "text-violet-500" },
    rose: { bg: "bg-rose-50 dark:bg-rose-500/10", border: "border-rose-200 dark:border-rose-500/20", text: "text-rose-600 dark:text-rose-400", icon: "text-rose-500" },
    navyAliasC: { bg: "bg-indigo-50 dark:bg-indigo-500/10", border: "border-indigo-200 dark:border-indigo-500/20", text: "text-indigo-600 dark:text-indigo-400", icon: "text-indigo-500" },
  };
  return colorMap[color] || colorMap.slate;
};

// ─── Main Page ───────────────────────────────────────────────────────────────
export default function TermsPage() {
  const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set());

  const toggleSection = (sectionId: string) => {
    const newExpanded = new Set(expandedSections);
    if (newExpanded.has(sectionId)) {
      newExpanded.delete(sectionId);
    } else {
      newExpanded.add(sectionId);
    }
    setExpandedSections(newExpanded);

    // Scroll to section after a brief delay to allow expansion animation
    setTimeout(() => {
      const element = document.getElementById(`section-${sectionId}`);
      if (element) {
        element.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    }, 100);
  };
  return (
    <div className="min-h-screen bg-background text-foreground font-sans overflow-x-hidden transition-colors duration-300">

      {/* Ambient background orbs */}
      <div className="fixed inset-0 pointer-events-none z-0 overflow-hidden">
        <div className="absolute top-[-20%] left-[10%] w-[600px] h-[600px] rounded-full bg-[radial-gradient(circle,color-mix(in_srgb,var(--brand)_8%,transparent)_0%,transparent_65%)] blur-[40px]" />
        <div className="absolute bottom-[5%] right-[-10%] w-[500px] h-[500px] rounded-full bg-[radial-gradient(circle,color-mix(in_srgb,var(--brand)_8%,transparent)_0%,transparent_65%)] blur-[40px]" />
      </div>

      <div className="relative z-10 max-w-3xl mx-auto px-6 pb-28">

        {/* ── Hero ── */}
        <section className="pt-16 pb-12 text-center">
          <motion.div {...fadeUp(0)} className="flex justify-center mb-7">
            <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-indigo-50 dark:bg-indigo-500/10 border border-indigo-100 dark:border-indigo-500/20 text-[12px] font-bold tracking-wider uppercase text-indigo-600 dark:text-[var(--brand-text)]">
              <FiFileText size={11} />
              Legal
            </span>
          </motion.div>

          <motion.h1
            {...fadeUp(0.08)}
            className="text-[clamp(32px,5.5vw,56px)] font-black tracking-tight leading-[1.05] text-slate-900 dark:text-white mb-4"
          >
            Terms of{" "}
            <span className="bg-gradient-to-r from-indigo-500 to-violet-500 bg-clip-text text-transparent">
              Service
            </span>
          </motion.h1>

          <motion.p {...fadeUp(0.16)} className="text-sm text-slate-400 dark:text-slate-500 font-medium">
            Last updated: {lastUpdated}
          </motion.p>
        </section>

        {/* ── TL;DR banner ── */}
        <motion.div
          {...fadeUp(0.22)}
          className="mb-12 p-5 rounded-2xl bg-indigo-50 dark:bg-indigo-500/10 border border-indigo-200 dark:border-indigo-500/20 flex gap-4"
        >
          <div className="w-9 h-9 rounded-xl bg-indigo-100 dark:bg-indigo-500/20 flex items-center justify-center shrink-0 mt-0.5">
            <FiFileText size={16} className="text-indigo-600 dark:text-[var(--brand-text)]" />
          </div>
          <div>
            <p className="text-sm font-bold text-indigo-800 dark:text-indigo-300 mb-1">TL;DR: Free to use, don't abuse it.</p>
            <p className="text-sm text-indigo-700 dark:text-[var(--brand-text)] leading-relaxed">
              Average Grade Calculator is free for personal, non-commercial use. Don't scrape it, attack it, or resell it. Results are provided as-is, always verify important figures with a professional.
            </p>
          </div>
        </motion.div>

        {/* Feature Cards */}
        <motion.div
          {...fadeUp(0.28)}
          className="mb-12 grid sm:grid-cols-2 lg:grid-cols-4 gap-4"
        >
          {features.map((feature, i) => (
            <div key={feature.title} className="p-5 rounded-2xl bg-white dark:bg-slate-900/40 border border-slate-200 dark:border-white/5">
              <div className="flex items-center gap-3 mb-3">
                {feature.icon}
                <h3 className="text-sm font-bold text-slate-900 dark:text-white">{feature.title}</h3>
              </div>
              <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">{feature.description}</p>
            </div>
          ))}
        </motion.div>

        {/* Quick Navigation */}
        <motion.div
          {...fadeUp(0.32)}
          className="mb-8 p-5 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700"
        >
          <h3 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-4">Quick Nav</h3>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
            {sections.map((section) => {
              const colors = getColorClasses(section.color);
              const IconComponent = section.icon;
              return (
                <button
                  key={section.id}
                  onClick={() => toggleSection(section.id)}
                  className={`flex items-center justify-between gap-3 p-3 rounded-xl border text-left transition-all duration-200 hover:scale-105 ${
                    expandedSections.has(section.id) 
                      ? `${colors.bg} ${colors.border} shadow-sm` 
                      : 'bg-white dark:bg-slate-700 border-slate-200 dark:border-slate-600 hover:bg-slate-50 dark:hover:bg-slate-600'
                  }`}
                >
                  <div className="flex items-center gap-3 min-w-0">
                    <IconComponent 
                      className={expandedSections.has(section.id) ? colors.icon : 'text-slate-400 dark:text-slate-500'} 
                      size={16} 
                    />
                    <span className={`text-xs font-medium ${
                      expandedSections.has(section.id) 
                        ? colors.text 
                        : 'text-slate-600 dark:text-slate-400'
                    }`}>
                      {getLegalNavLabel(section.id, section.title)}
                    </span>
                  </div>
                  <FiArrowRight
                    size={14}
                    className={`shrink-0 transition-transform duration-200 ${
                      expandedSections.has(section.id)
                        ? `${colors.icon} translate-x-0.5`
                        : 'text-slate-300 dark:text-slate-500'
                    }`}
                  />
                </button>
              );
            })}
          </div>
        </motion.div>

        {/* Interactive Sections */}
        <div className="space-y-6">
          {sections.map((section, i) => {
            const isExpanded = expandedSections.has(section.id);
            const colors = getColorClasses(section.color);
            const IconComponent = section.icon;
            
            return (
              <motion.div
                key={section.id}
                id={`section-${section.id}`}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-40px" }}
                transition={{ duration: 0.45, delay: i * 0.05, ease: [0.22, 1, 0.36, 1] }}
                className={`rounded-2xl border ${colors.border} ${colors.bg} overflow-hidden scroll-mt-24`}
              >
                {/* Section Header */}
                <button
                  onClick={() => toggleSection(section.id)}
                  className="w-full p-6 text-left hover:bg-black/5 dark:hover:bg-white/5 transition-colors duration-200"
                >
                  <div className="flex items-start gap-4">
                    <div className={`w-10 h-10 rounded-xl ${colors.bg} border ${colors.border} flex items-center justify-center shrink-0`}>
                      <IconComponent className={colors.icon} size={20} />
                    </div>
                    
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between gap-3 mb-2">
                        <h3 className="text-lg font-bold text-slate-900 dark:text-white">{section.title}</h3>
                        <div className="flex items-center gap-2 shrink-0">
                          {isExpanded && (
                            <span className="px-2 py-1 text-xs font-medium bg-green-100 dark:bg-green-500/20 text-green-700 dark:text-green-300 rounded-full">
                              Read
                            </span>
                          )}
                          {isExpanded ? (
                            <FiChevronUp className="text-slate-400 dark:text-slate-500" size={18} />
                          ) : (
                            <FiChevronDown className="text-slate-400 dark:text-slate-500" size={18} />
                          )}
                        </div>
                      </div>
                      
                      <p className={`text-sm ${colors.text} mb-3`}>{section.summary}</p>
                      
                      {/* Key highlights - always visible */}
                      <div className="flex flex-wrap gap-2">
                        {section.highlights.slice(0, 3).map((highlight, idx) => (
                          <span key={idx} className="px-3 py-1 text-xs font-medium bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-600 text-slate-600 dark:text-slate-300 rounded-full">
                            {highlight}
                          </span>
                        ))}
                      </div>
                    </div>
                  </div>
                </button>

                {/* Expanded Content */}
                <motion.div
                  initial={false}
                  animate={{ height: isExpanded ? "auto" : 0 }}
                  transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
                  className="overflow-hidden"
                >
                  <div className="px-4 pb-6 sm:px-6">
                    <div className="min-w-0 sm:pl-14">
                      
                      {/* Main content */}
                      <div className="prose prose-sm max-w-none min-w-0">
                        <p className="break-words text-sm text-slate-600 dark:text-slate-400 leading-relaxed mb-4 whitespace-pre-line">
                          <LinkedText text={section.content} />
                        </p>
                      </div>

                      {/* Prohibited Activities */}
                      {section.prohibitedActivities && (
                        <div className="mt-4">
                          <h4 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">Prohibited Activities:</h4>
                          <div className="grid gap-2">
                            {section.prohibitedActivities.map((activity, idx) => (
                              <div key={idx} className="flex items-center gap-2 text-xs text-slate-600 dark:text-slate-400">
                                <div className="w-1.5 h-1.5 rounded-full bg-red-400" />
                                {activity}
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                      {/* AdSense Policies */}
                      {section.adSensePolicies && (
                        <div className="mt-4 space-y-2">
                          <h4 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">Advertising Terms:</h4>
                          {section.adSensePolicies.map((policy, idx) => (
                            <div key={idx} className="min-w-0 p-3 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-600">
                              <p className="text-sm font-medium text-slate-800 dark:text-slate-200 mb-1">{policy.policy}</p>
                              <p className="break-words text-xs text-slate-500 dark:text-slate-400">{policy.description}</p>
                            </div>
                          ))}
                        </div>
                      )}

                      {/* Not Advice Types */}
                      {section.notAdviceTypes && (
                        <div className="mt-4">
                          <h4 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">Not professional advice for:</h4>
                          <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                            {section.notAdviceTypes.map((type, idx) => (
                              <div key={idx} className="flex items-center gap-2 text-xs text-slate-600 dark:text-slate-400">
                                <div className="w-1.5 h-1.5 rounded-full bg-amber-400" />
                                {type}
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                      {/* Excluded Damages */}
                      {section.excludedDamages && (
                        <div className="mt-4">
                          <h4 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">Not liable for:</h4>
                          <div className="grid sm:grid-cols-2 gap-2">
                            {section.excludedDamages.map((damage, idx) => (
                              <div key={idx} className="flex items-center gap-2 text-xs text-slate-600 dark:text-slate-400">
                                <div className="w-1.5 h-1.5 rounded-full bg-red-400" />
                                {damage}
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                      {/* Contact Methods */}
                      {section.contactMethods && (
                        <div className="mt-4 space-y-2">
                          <h4 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">Contact Details:</h4>
                          {section.contactMethods.map((method, idx) => (
                            <div key={idx} className="flex flex-col gap-2 p-3 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-600 sm:flex-row sm:items-center sm:justify-between">
                              <div className="flex shrink-0 items-center gap-3">
                                <FiMail className="text-indigo-500 shrink-0" size={16} />
                                <div>
                                  <span className="text-sm font-medium text-slate-700 dark:text-slate-300">{method.type}</span>
                                </div>
                              </div>
                              <div className="min-w-0 sm:max-w-[70%]">
                                <ContactMethodLink type={method.type} value={method.value} />
                              </div>
                            </div>
                          ))}
                        </div>
                      )}

                    </div>
                  </div>
                </motion.div>
              </motion.div>
            );
          })}
        </div>

        {/* Key Takeaways Summary */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.45, ease: [0.22, 1, 0.36, 1] }}
          className="mt-12 p-6 rounded-2xl bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-800 dark:to-slate-900 border border-slate-200 dark:border-slate-700"
        >
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl bg-indigo-100 dark:bg-indigo-500/20 flex items-center justify-center">
              <FiBook className="text-indigo-600 dark:text-[var(--brand-text)]" size={20} />
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-900 dark:text-white">Key Takeaways</h3>
              <p className="text-sm text-slate-600 dark:text-slate-400">Essential terms to remember</p>
            </div>
          </div>
          
          <div className="grid md:grid-cols-2 gap-4">
            {[
              {
                icon: FiGlobe,
                title: "Free Service",
                desc: "The website is provided at no cost for personal, non-commercial use",
                color: "text-green-500"
              },
              {
                icon: FiShield,
                title: "Limited Liability", 
                desc: "Maximum liability is zero - verify results independently",
                color: "text-red-500"
              },
              {
                icon: FiLock,
                title: "No Data Storage",
                desc: "No accounts required, calculations done locally in browser",
                color: "text-purple-500"
              },
              {
                icon: FiUsers,
                title: "Lawful Use Only",
                desc: "Personal use permitted - no scraping, attacking, or commercial resale",
                color: "text-blue-500"
              }
            ].map((item, idx) => (
              <div key={idx} className="flex gap-3 p-4 rounded-xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-600">
                <item.icon className={`${item.color} mt-0.5`} size={18} />
                <div>
                  <p className="text-sm font-semibold text-slate-800 dark:text-slate-200 mb-1">{item.title}</p>
                  <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">{item.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </motion.div>

        {/* ── Related policies ── */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.45, ease: [0.22, 1, 0.36, 1] }}
          className="mt-16 grid sm:grid-cols-3 gap-4"
        >
          {[
            { label: "Privacy",  href: ROUTES.privacyPolicy,    desc: "How we handle your data." },
            { label: "Cookies",   href: ROUTES.cookies,    desc: "Browser storage details." },
            { label: "Disclaimer",      href: ROUTES.disclaimer, desc: "Website limitations." },
          ].map((link) => (
            <Link
              key={link.href}
              href={link.href}
              className="group flex items-center justify-between gap-3 px-4 py-4 rounded-2xl border border-slate-200 dark:border-white/5 bg-white dark:bg-slate-900/40 hover:border-indigo-300 dark:hover:border-indigo-500/30 hover:bg-indigo-50/30 dark:hover:bg-indigo-500/5 transition-all duration-200"
            >
              <div>
                <p className="text-sm font-bold text-slate-900 dark:text-white mb-0.5">{link.label}</p>
                <p className="text-xs text-slate-500 dark:text-slate-400">{link.desc}</p>
              </div>
              <FiArrowRight size={14} className="text-slate-300 dark:text-slate-600 group-hover:text-indigo-500 group-hover:translate-x-0.5 transition-all duration-200 shrink-0" />
            </Link>
          ))}
        </motion.div>

        <div className="mt-8">
          <GlobalCTA
            title="Questions about these"
            highlightText="Terms?"
            subtitle="We are happy to clarify anything. Send us a message and we will get back to you."
            badgeText="Legal support • Clear answers"
            primaryBtnText="Contact Us"
            secondaryBtnText="Privacy"
            primaryLink={ROUTES.contact}
            secondaryLink={ROUTES.privacyPolicy}
          />
        </div>

      </div>

      <style>{`
        @media (prefers-reduced-motion: reduce) {
          * { animation: none !important; transition: none !important; }
        }
      `}</style>
    </div>
  );
}
