'use client';

import { motion } from "framer-motion";
import Link from "next/link";
import { useState } from "react";
import type { IconType } from "react-icons";
import { FiArrowRight, FiAlertTriangle, FiShield, FiAlertCircle, FiChevronDown, FiChevronUp, FiBook, FiDollarSign, FiLock, FiExternalLink, FiClock, FiMail, FiFileText } from "react-icons/fi";
import PageHeader from "@/components/ui/PageHeader";
import FeatureCards from "@/components/sections/FeatureCards";
import InfoSection from "@/components/sections/InfoSection";
import GlobalCTA from "@/components/ui/GlobalCTA";
import { ROUTES } from "@/lib/routes";
import { ContactMethodLink } from "@/components/ui/ContactMethodLink";
import { LinkedText } from "@/components/ui/LinkedText";
import { getLegalNavLabel } from "@/lib/legalNav";

// ─── Data ────────────────────────────────────────────────────────────────────
const lastUpdated = "July 8, 2026";

const features = [
  {
    icon: <FiAlertCircle className="text-amber-500" size={28} />,
    title: "Information Only",
    description: "Results are estimates",
  },
  {
    icon: <FiBook className="text-blue-500" size={28} />,
    title: "No Advice",
    description: "Verify independently",
  },
  {
    icon: <FiShield className="text-red-500" size={28} />,
    title: "Limited Liability",
    description: "Use results carefully",
  },
];

interface DisclaimerSection {
  id: string;
  title: string;
  icon: IconType;
  color: string;
  summary: string;
  content: string;
  highlights: string[];
  adviceTypes?: Array<{
    type: string;
    desc: string;
  }>;
  responsibilities?: string[];
  details?: Array<{
    type: string;
    desc: string;
  }>;
  variationReasons?: string[];
  damageTypes?: string[];
  contactMethods?: Array<{
    type: string;
    value: string;
  }>;
  securityNote?: string;
}

const sections: DisclaimerSection[] = [
  {
    id: "general",
    title: "1. General Information Only",
    icon: FiAlertCircle,
    color: "amber",
    summary: "Website results are provided for informational purposes only",
    content: `Average Grade Calculator is provided for general informational and educational purposes only.

The results generated by this website are estimates and should not be treated as precise, professional, or legally binding figures. Always verify results independently before making any real-world decisions.`,
    highlights: [
      "Informational and educational purposes only",
      "Results are estimates, not precise figures", 
      "Always verify results independently"
    ]
  },
  {
    id: "professional",
    title: "2. No Professional Advice",
    icon: FiBook,
    color: "blue",
    summary: "Content does not constitute professional advice of any kind",
    content: `The content and results provided by Average Grade Calculator do not constitute professional advice of any kind.

Always consult a qualified professional relevant to your specific situation before acting on any website result.`,
    highlights: [
      "No professional advice",
      "No licensed expert advice", 
      "Always consult qualified professionals"
    ],
    adviceTypes: [
      {
        type: "Professional Advice",
        desc: "Website results cannot account for every detail of your specific situation."
      },
      {
        type: "Licensed Expert Advice", 
        desc: "Requirements and standards can vary by jurisdiction and change frequently."
      },
      {
        type: "Independent Verification",
        desc: "Always verify important results before relying on them."
      }
    ]
  },
  {
    id: "accuracy",
    title: "3. Accuracy & Errors",
    icon: FiShield,
    color: "green",
    summary: "No guarantees regarding accuracy, completeness, or reliability",
    content: `While we make every effort to keep results accurate and up to date, Average Grade Calculator makes no guarantees regarding the accuracy, completeness, or reliability of any result. Results may vary based on:

• User-provided input values
• Regional differences
• Changes in requirements or standards over time

Average Grade Calculator is not responsible for any errors, incorrect results, or outdated formulas. Use all results at your own risk.`,
    highlights: [
      "No guarantees on accuracy or reliability",
      "Results may vary by region and time",
      "Use all results at your own risk"
    ],
    variationReasons: [
      "User-provided input values",
      "Regional differences", 
      "Changes in requirements and standards over time",
      "Different input methods",
      "Source-specific calculation methods",
      "Outdated formulas or data"
    ]
  },
  {
    id: "liability",
    title: "4. Limitation of Liability", 
    icon: FiShield,
    color: "red",
    summary: "No liability for damages arising from website use",
    content: `To the fullest extent permitted by applicable law, Average Grade Calculator and its owners, employees, and contributors shall not be liable for any:

• Direct, indirect, or incidental damages
• Losses or incorrect decisions made based on website results
• Data loss or technical issues while using the site

You acknowledge that your use of this website is entirely at your own risk.`,
    highlights: [
      "No liability for direct or indirect damages",
      "No liability for losses or decisions",
      "Use of website is at your own risk"
    ],
    damageTypes: [
      "Direct, indirect, or incidental damages",
      "Losses or incorrect decisions", 
      "Data loss or technical issues",
      "Any consequences arising from website use"
    ]
  },
  {
    id: "advertising",
    title: "5. Advertising Disclosure",
    icon: FiDollarSign,
    color: "purple",
    summary: "Google AdSense advertising helps keep the website free",
    content: `This website displays advertisements served by Google AdSense and possibly other third-party ad networks. These ads help us keep the website free for all users.

• We do not control the content of ads displayed on our site
• Ad clicks and impressions are tracked by Google as per their Privacy Policy
• We may receive compensation when you click on or view ads displayed on this site

This disclosure is made in compliance with the Federal Trade Commission (FTC) guidelines.`,
    highlights: [
      "Ads help keep the website free",
      "We don't control ad content",
      "FTC compliance disclosure"
    ]
  },
  {
    id: "third-party",
    title: "6. Third-Party Links & Services",
    icon: FiExternalLink,
    color: "indigo",
    summary: "No responsibility for third-party websites or services",
    content: `Our website may contain links to third-party websites for reference or informational purposes. Average Grade Calculator has no control over the content, privacy policies, or practices of any third-party site and accepts no responsibility for them.

Visiting any third-party link from our website is done entirely at your own risk.`,
    highlights: [
      "Links provided for reference only",
      "No control over third-party content",
      "Visit third-party links at your own risk"
    ]
  },
  {
    id: "user-responsibility",
    title: "7. User Responsibility",
    icon: FiClock,
    color: "orange",
    summary: "Users are solely responsible for their website use",
    content: `You, the user, are solely responsible for:

• The accuracy of data you enter
• How you interpret and use the results
• Any decisions, actions, or consequences arising from your use of this website`,
    highlights: [
      "Responsible for data accuracy",
      "Responsible for result interpretation",
      "Responsible for all consequences"
    ],
    responsibilities: [
      "Accuracy of input data",
      "Proper interpretation of results",
      "Decisions based on website results",
      "Consequences of actions taken"
    ]
  },
  {
    id: "intellectual-property",
    title: "8. Intellectual Property",
    icon: FiFileText,
    color: "indigo",
    summary: "All content protected under copyright laws",
    content: `All content on Average Grade Calculator, including text, design, graphics, and code, is the intellectual property of Average Grade Calculator and is protected under applicable copyright laws. Unauthorized reproduction or distribution is strictly prohibited.`,
    highlights: [
      "All content is protected by copyright",
      "Includes text, design, graphics, and code", 
      "Unauthorized reproduction prohibited"
    ]
  },
  {
    id: "changes",
    title: "9. Changes to This Disclaimer",
    icon: FiBook,
    color: "indigo",
    summary: "Disclaimer may be updated without prior notice",
    content: `We reserve the right to update or modify this Disclaimer at any time without prior notice. The "Last Updated" date at the top of this page will reflect any changes. Continued use of the website after any changes constitutes your acceptance of the updated Disclaimer.`,
    highlights: [
      "Updates without prior notice",
      "Last updated date reflects changes", 
      "Continued use implies acceptance"
    ]
  },
  {
    id: "contact",
    title: "10. Contact Us",
    icon: FiMail,
    color: "indigo",
    summary: "Questions about this disclaimer welcomed",
    content: `For questions about this Disclaimer, contact the Average Grade Calculator team.
Use the contact options below for support.`,
    highlights: [
      "Disclaimer support",
      "Website and email",
      "Prompt response"
    ],
    contactMethods: [
      { type: "Email", value: "support@averagegradecalculator.com" },
      { type: "Website", value: "https://www.averagegradecalculator.com" }
    ]
  },
];

// ─── Helper Functions ────────────────────────────────────────────────────────
const getColorClasses = (color: string) => {
  const colorMap: Record<string, { bg: string; border: string; text: string; icon: string }> = {
    amber: { bg: "bg-amber-50 dark:bg-amber-500/10", border: "border-amber-200 dark:border-amber-500/20", text: "text-amber-600 dark:text-amber-400", icon: "text-amber-500" },
    blue: { bg: "bg-blue-50 dark:bg-blue-500/10", border: "border-blue-200 dark:border-blue-500/20", text: "text-blue-600 dark:text-blue-400", icon: "text-blue-500" },
    green: { bg: "bg-green-50 dark:bg-green-500/10", border: "border-green-200 dark:border-green-500/20", text: "text-green-600 dark:text-green-400", icon: "text-green-500" },
    purple: { bg: "bg-purple-50 dark:bg-purple-500/10", border: "border-purple-200 dark:border-purple-500/20", text: "text-purple-600 dark:text-purple-400", icon: "text-purple-500" },
    indigo: { bg: "bg-indigo-50 dark:bg-indigo-500/10", border: "border-indigo-200 dark:border-indigo-500/20", text: "text-indigo-600 dark:text-[var(--brand-text)]", icon: "text-indigo-500" },
    orange: { bg: "bg-orange-50 dark:bg-orange-500/10", border: "border-orange-200 dark:border-orange-500/20", text: "text-orange-600 dark:text-orange-400", icon: "text-orange-500" },
    red: { bg: "bg-red-50 dark:bg-red-500/10", border: "border-red-200 dark:border-red-500/20", text: "text-red-600 dark:text-red-400", icon: "text-red-500" },
    slate: { bg: "bg-slate-50 dark:bg-slate-500/10", border: "border-slate-200 dark:border-slate-500/20", text: "text-slate-600 dark:text-slate-400", icon: "text-slate-500" },
    navyAliasB: { bg: "bg-indigo-50 dark:bg-indigo-500/10", border: "border-indigo-200 dark:border-indigo-500/20", text: "text-indigo-600 dark:text-[var(--brand-text)]", icon: "text-indigo-500" },
  };
  return colorMap[color] || colorMap.slate;
};

// ─── Main Page ───────────────────────────────────────────────────────────────
export default function DisclaimerPage() {
  const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set());

  const toggleSection = (sectionId: string) => {
    const newExpanded = new Set(expandedSections);
    if (newExpanded.has(sectionId)) {
      newExpanded.delete(sectionId);
    } else {
      newExpanded.add(sectionId);
    }
    setExpandedSections(newExpanded);

    // Scroll to section after a brief delay to allow expansion animation
    setTimeout(() => {
      const element = document.getElementById(`section-${sectionId}`);
      if (element) {
        element.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    }, 100);
  };
  return (
    <div className="min-h-screen bg-background text-foreground font-sans overflow-x-hidden transition-colors duration-300">

      {/* Ambient background orbs */}
      <div className="fixed inset-0 pointer-events-none z-0 overflow-hidden">
        <div className="absolute top-[-20%] left-[10%] w-[600px] h-[600px] rounded-full bg-[radial-gradient(circle,color-mix(in_srgb,var(--brand)_8%,transparent)_0%,transparent_65%)] blur-[40px]" />
        <div className="absolute bottom-[5%] right-[-10%] w-[500px] h-[500px] rounded-full bg-[radial-gradient(circle,color-mix(in_srgb,var(--brand)_8%,transparent)_0%,transparent_65%)] blur-[40px]" />
      </div>

      <div className="relative z-10 max-w-4xl mx-auto px-6 pb-28">

        {/* Page Header */}
        <PageHeader 
          title="Disclaimer" 
          subtitle="Important Legal Information and Limitations for Average Grade Calculator" 
          lastUpdated={lastUpdated} 
        />

        {/* Feature Cards */}
        <FeatureCards features={features} />

        {/* Info Section */}
        <div className="mb-8 p-5 rounded-2xl bg-red-50 dark:bg-red-500/10 border-red-200 dark:border-red-500/20 flex gap-4">
          <div className="w-9 h-9 rounded-xl bg-red-100 dark:bg-red-500/20 flex items-center justify-center shrink-0 mt-0.5">
            <span className="text-red-600 dark:text-red-400">
              <FiAlertTriangle />
            </span>
          </div>
          <div>
            <p className="text-sm font-bold text-red-800 dark:text-red-300 mb-1">Important Notice</p>
            <p className="text-sm text-red-700 dark:text-red-400 leading-relaxed whitespace-pre-line">
              Average Grade Calculator is provided for general informational and educational purposes only. The results are estimates and should not be treated as precise, professional, or legally binding figures.

Always verify results independently and consult qualified professionals before making important decisions based on website results.
            </p>
          </div>
        </div>

        {/* Quick Navigation */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.45, ease: [0.22, 1, 0.36, 1] }}
          className="mb-8 p-5 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700"
        >
          <h3 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-4">Quick Nav</h3>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {sections.map((section) => {
              const colors = getColorClasses(section.color);
              const IconComponent = section.icon;
              return (
                <button
                  key={section.id}
                  onClick={() => toggleSection(section.id)}
                  className={`flex items-center justify-between gap-3 p-3 rounded-xl border text-left transition-all duration-200 hover:scale-105 ${
                    expandedSections.has(section.id) 
                      ? `${colors.bg} ${colors.border} shadow-sm` 
                      : 'bg-white dark:bg-slate-700 border-slate-200 dark:border-slate-600 hover:bg-slate-50 dark:hover:bg-slate-600'
                  }`}
                >
                  <div className="flex items-center gap-3 min-w-0">
                    <IconComponent 
                      className={expandedSections.has(section.id) ? colors.icon : 'text-slate-400 dark:text-slate-500'} 
                      size={16} 
                    />
                    <span className={`text-xs font-medium ${
                      expandedSections.has(section.id) 
                        ? colors.text 
                        : 'text-slate-600 dark:text-slate-400'
                    }`}>
                      {getLegalNavLabel(section.id, section.title)}
                    </span>
                  </div>
                  <FiArrowRight
                    size={14}
                    className={`shrink-0 transition-transform duration-200 ${
                      expandedSections.has(section.id)
                        ? `${colors.icon} translate-x-0.5`
                        : 'text-slate-300 dark:text-slate-500'
                    }`}
                  />
                </button>
              );
            })}
          </div>
        </motion.div>

        {/* Interactive Sections */}
        <div className="space-y-6">
          {sections.map((section, i) => {
            const isExpanded = expandedSections.has(section.id);
            const colors = getColorClasses(section.color);
            const IconComponent = section.icon;
            
            return (
              <motion.div
                key={section.id}
                id={`section-${section.id}`}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-40px" }}
                transition={{ duration: 0.45, delay: i * 0.05, ease: [0.22, 1, 0.36, 1] }}
                className={`rounded-2xl border ${colors.border} ${colors.bg} overflow-hidden scroll-mt-24`}
              >
                {/* Section Header */}
                <button
                  onClick={() => toggleSection(section.id)}
                  className="w-full p-6 text-left hover:bg-black/5 dark:hover:bg-white/5 transition-colors duration-200"
                >
                  <div className="flex items-start gap-4">
                    <div className={`w-10 h-10 rounded-xl ${colors.bg} border ${colors.border} flex items-center justify-center shrink-0`}>
                      <IconComponent className={colors.icon} size={20} />
                    </div>
                    
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between gap-3 mb-2">
                        <h3 className="text-lg font-bold text-slate-900 dark:text-white">{section.title}</h3>
                        <div className="flex items-center gap-2 shrink-0">
                          {isExpanded && (
                            <span className="px-2 py-1 text-xs font-medium bg-green-100 dark:bg-green-500/20 text-green-700 dark:text-green-300 rounded-full">
                              Read
                            </span>
                          )}
                          {isExpanded ? (
                            <FiChevronUp className="text-slate-400 dark:text-slate-500" size={18} />
                          ) : (
                            <FiChevronDown className="text-slate-400 dark:text-slate-500" size={18} />
                          )}
                        </div>
                      </div>
                      
                      <p className={`text-sm ${colors.text} mb-3`}>{section.summary}</p>
                      
                      {/* Key highlights - always visible */}
                      <div className="flex flex-wrap gap-2">
                        {section.highlights.slice(0, 3).map((highlight, idx) => (
                          <span key={idx} className="px-3 py-1 text-xs font-medium bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-600 text-slate-600 dark:text-slate-300 rounded-full">
                            {highlight}
                          </span>
                        ))}
                      </div>
                    </div>
                  </div>
                </button>

                {/* Expanded Content */}
                <motion.div
                  initial={false}
                  animate={{ height: isExpanded ? "auto" : 0 }}
                  transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
                  className="overflow-hidden"
                >
                  <div className="px-4 pb-6 sm:px-6">
                    <div className="min-w-0 sm:pl-14">
                      
                      {/* Main content */}
                      <div className="prose prose-sm max-w-none min-w-0">
                        <p className="break-words text-sm text-slate-600 dark:text-slate-400 leading-relaxed mb-4">
                          <LinkedText text={section.content} />
                        </p>
                      </div>

                      {/* Special content based on section */}
                      {section.adviceTypes && (
                        <div className="mt-4 space-y-3">
                          <h4 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">We do not provide:</h4>
                          {section.adviceTypes.map((advice, idx) => (
                            <div key={idx} className="flex gap-3 p-3 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-600">
                              <div className="w-2 h-2 rounded-full bg-red-400 mt-2 shrink-0" />
                              <div>
                                <p className="text-sm font-medium text-slate-800 dark:text-slate-200 mb-1">{advice.type}</p>
                                <p className="text-xs text-slate-600 dark:text-slate-400">{advice.desc}</p>
                              </div>
                            </div>
                          ))}
                        </div>
                      )}

                      {section.responsibilities && (
                        <div className="mt-4">
                          <h4 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">You are responsible for:</h4>
                          <div className="grid sm:grid-cols-2 gap-2">
                            {section.responsibilities.map((responsibility, idx) => (
                              <div key={idx} className="flex items-center gap-2 text-xs text-slate-600 dark:text-slate-400">
                                <div className="w-1.5 h-1.5 rounded-full bg-orange-400" />
                                {responsibility}
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                      {section.details && (
                        <div className="mt-4 space-y-3">
                          <h4 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">Specific Areas:</h4>
                          {section.details.map((detail, idx) => (
                            <div key={idx} className="flex gap-3 p-3 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-600">
                              <div className="w-2 h-2 rounded-full bg-indigo-400 mt-2 shrink-0" />
                              <div>
                                <p className="text-sm font-medium text-slate-800 dark:text-slate-200 mb-1">{detail.type}</p>
                                <p className="text-xs text-slate-600 dark:text-slate-400">{detail.desc}</p>
                              </div>
                            </div>
                          ))}
                        </div>
                      )}

                      {section.variationReasons && (
                        <div className="mt-4">
                          <h4 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">Results may vary due to:</h4>
                          <div className="grid sm:grid-cols-2 gap-2">
                            {section.variationReasons.map((reason, idx) => (
                              <div key={idx} className="flex items-center gap-2 text-xs text-slate-600 dark:text-slate-400">
                                <div className="w-1.5 h-1.5 rounded-full bg-orange-400" />
                                {reason}
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                      {section.damageTypes && (
                        <div className="mt-4">
                          <h4 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">Not liable for damages including:</h4>
                          <div className="grid sm:grid-cols-2 gap-2">
                            {section.damageTypes.map((damage, idx) => (
                              <div key={idx} className="flex items-center gap-2 text-xs text-slate-600 dark:text-slate-400">
                                <div className="w-1.5 h-1.5 rounded-full bg-red-400" />
                                {damage}
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                      {section.contactMethods && (
                        <div className="mt-4 space-y-2">
                          <h4 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">Contact Methods:</h4>
                          {section.contactMethods.map((method, idx) => (
                            <div key={idx} className="flex flex-col gap-2 p-3 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-600 sm:flex-row sm:items-center sm:justify-between">
                              <div className="flex shrink-0 items-center gap-3">
                                <FiMail className="text-indigo-500 shrink-0" size={16} />
                                <span className="text-sm font-medium text-slate-700 dark:text-slate-300">{method.type}</span>
                              </div>
                              <div className="min-w-0 sm:max-w-[70%]">
                                <ContactMethodLink type={method.type} value={method.value} />
                              </div>
                            </div>
                          ))}
                        </div>
                      )}

                      {section.securityNote && (
                        <div className="mt-4 p-4 rounded-lg bg-purple-50 dark:bg-purple-500/10 border border-purple-200 dark:border-purple-500/20">
                          <div className="flex gap-3">
                            <FiLock className="text-purple-500 mt-0.5" size={16} />
                            <div>
                              <p className="text-sm font-medium text-purple-800 dark:text-purple-300 mb-1">Security Note</p>
                              <p className="text-sm text-purple-700 dark:text-purple-400">{section.securityNote}</p>
                            </div>
                          </div>
                        </div>
                      )}

                    </div>
                  </div>
                </motion.div>
              </motion.div>
            );
          })}
        </div>

        {/* Key Takeaways Summary */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.45, ease: [0.22, 1, 0.36, 1] }}
          className="mt-12 p-6 rounded-2xl bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-800 dark:to-slate-900 border border-slate-200 dark:border-slate-700"
        >
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl bg-indigo-100 dark:bg-indigo-500/20 flex items-center justify-center">
              <FiBook className="text-indigo-600 dark:text-[var(--brand-text)]" size={20} />
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-900 dark:text-white">Key Takeaways</h3>
              <p className="text-sm text-slate-600 dark:text-slate-400">Essential points to remember</p>
            </div>
          </div>
          
          <div className="grid md:grid-cols-2 gap-4">
            {[
              {
                icon: FiAlertTriangle,
                title: "Informational Use Only",
                desc: "All results are estimates for educational purposes - verify independently",
                color: "text-amber-500"
              },
              {
                icon: FiShield,
                title: "Limited Liability", 
                desc: "We're not responsible for decisions or damages based on website results",
                color: "text-red-500"
              },
              {
                icon: FiBook,
                title: "No Professional Advice",
                desc: "Results do not constitute professional counsel",
                color: "text-blue-500"
              },
              {
                icon: FiDollarSign,
                title: "Advertising Disclosure",
                desc: "We display ads to keep the website free - FTC compliant disclosure",
                color: "text-purple-500"
              }
            ].map((item, idx) => (
              <div key={idx} className="flex gap-3 p-4 rounded-xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-600">
                <item.icon className={`${item.color} mt-0.5`} size={18} />
                <div>
                  <p className="text-sm font-semibold text-slate-800 dark:text-slate-200 mb-1">{item.title}</p>
                  <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">{item.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Related policies */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.45, ease: [0.22, 1, 0.36, 1] }}
          className="mt-16 grid sm:grid-cols-3 gap-4"
        >
          {[
            { label: "Privacy",  href: ROUTES.privacyPolicy,  desc: "How we handle your data." },
            { label: "Cookies",   href: ROUTES.cookies,  desc: "Browser storage details." },
            { label: "Terms",href: ROUTES.terms,    desc: "Rules for using this site." },
          ].map((link) => (
            <Link
              key={link.href}
              href={link.href}
              className="group flex items-center justify-between gap-3 px-4 py-4 rounded-2xl border border-slate-200 dark:border-white/5 bg-white dark:bg-slate-900/50 hover:border-indigo-300 dark:hover:border-indigo-500/30 hover:bg-indigo-50/30 dark:hover:bg-indigo-500/5 transition-all duration-200"
            >
              <div>
                <p className="text-sm font-bold text-slate-900 dark:text-white mb-0.5">{link.label}</p>
                <p className="text-xs text-slate-500 dark:text-slate-400">{link.desc}</p>
              </div>
              <FiArrowRight size={14} className="text-slate-300 dark:text-slate-600 group-hover:text-indigo-500 group-hover:translate-x-0.5 transition-all duration-200 shrink-0" />
            </Link>
          ))}
        </motion.div>

        <div className="mt-8">
          <GlobalCTA
            title="Questions about our"
            highlightText="disclaimer?"
            subtitle="If you need clarification about our limitations or have concerns about result accuracy, we're here to help."
            badgeText="Transparency first • Accuracy matters • Quick response"
            primaryBtnText="Contact Us"
            secondaryBtnText="Report an Issue"
            primaryLink={ROUTES.contact}
            secondaryLink={ROUTES.contact}
          />
        </div>

      </div>

      <style>{`
        @media (prefers-reduced-motion: reduce) {
          * { animation: none !important; transition: none !important; }
        }
      `}</style>
    </div>
  );
}
